apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:IC3GMigJ6mWgyYff8ck=,iv:Tp0u+K1wMqCNeeRDRiOjGzQRlJIXzqtlLtN3S3hx2Ug=,tag:Too8iKXaTTfNvmPXR05GcQ==,type:str]
    api-key: ENC[AES256_GCM,data:sSbciwH83ESx00YzjpZJgV7uSxCdc/LSm6Uz10ohokaWrl7TkQ==,iv:+6MSYVe8+MR18iPaUZtdgsCuLmcU1B6xQVx3J4PFXYs=,tag:mw4APoizCPjiY4d6JPhfBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14z0x4h5rpvjsyhs5ut7vng6rtza6rhdd45e23y77x927qzm803asscmlmk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPL2dHbVAzYWE0UUhSdlN2
            Ulg5a3FDVjdhQkp4SnIvTVlnek5XTUxYZFRBClZOVHpFTjBENW1HdExJQ00yYnZY
            VTNGdzlsR25FZEtIWm00OUt1TytOT0UKLS0tIEJVamRFYm9sSTBWMWtyU0IvWVIy
            OU15S2pZWDhMQ1BLb3hVM3BabkVoalUKXvLt3LUt9W+n8oh/k1ServQtcGB2q10Q
            aIZS46cvOO60y9FlMOG9Z5Ap74DrdAvapEMnSnqaI/EO0cVM+6D0RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-18T05:56:37Z"
    mac: ENC[AES256_GCM,data:GUTlvAJ2a7994JcuagLTpmW4Tv3oqGDIuFNp++0o4GwJA0IJcJq4aZ+xE3FLREXe92kjGtelb4kNb8Lk96/IezkbQlEBiyxDcDzFVMq0B6QdUuAhHr4rmrlBzU+KZo+6LcBl6kKb9HZTpfK0yvS1iqMJaClAJvAQ2ub8nIVyawQ=,iv:BboIyT1wrs38QuUnBiGJUBs4Xpn1pLykZ40n2FQ1UMM=,tag:bLxjMKNeO7IYf9pLvWibvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
