apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MizIuohbQ5s=,iv:SrbHHGnr0U3lIC5NJPq0Lo0AXFKduX6gwLknR2JQDOg=,tag:H2PTjDpcJTPOJ6mH+Vr98w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:dFjTQJkXvnlLWRymsvo=,iv:YI4MKHK2nUaKeDupp17ibB4rjeDWmnsWYDNCjr1JPEg=,tag:5ADsXhcGG1qPaEimOfcL+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14z0x4h5rpvjsyhs5ut7vng6rtza6rhdd45e23y77x927qzm803asscmlmk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeUFiOXlucWhWSlduY3RP
            OEpTNldvTDBhNExOR01yL29kNUlLNDBET2hjCkdLd0VJTlNVcStRbGh2K0ZENVJq
            RXlldVpYaE54ZkNXV0JJL0Y2anQxaGcKLS0tIDl4clNkSTQySDY3MEo0TEgydHk3
            MTVTYXNmVGRMbEJoUWxpd21RYUNldUkKuxXCQYt37rmX8XW4iIqnWKZydl+OQzbS
            8g4+XocRrliLhWNleyR0rM5ZzTfCTCIkuwf9xQ1a6sw05XPqGvRcRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-18T05:56:37Z"
    mac: ENC[AES256_GCM,data:oVwSGj4EOcdmAUhjGw5pOhiiLeQ8aKpDaG6L6IcqzEGld77mRCWouK2XE+KYeItb2pCCjJKedOYp1lh0K/Q7lEcTrhs19TfVoJqrViO9QTT+vqp4Bl4R+/3rgjsHFzRs6ihrA+2LDCKGMenzE1NnaQq8u/AnFHTpjQoxM3Xjobg=,iv:lJPrVtquX7ZODLoJuKjuiGPa3jGNnEXGX1tNTc7VIEQ=,tag:6l6jfDzXRD1fWDGF21DW7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
